#!/usr/bin/env bash
# Claude Memory Gateway: stops long Claude Code sessions from forgetting.
#
# One self-contained file. Installs hooks into ~/.claude so EVERY Claude Code
# session, in every repo, gets:
#   - handoff notes (.claude/memory/NOTES.md) loaded at start and after compaction
#   - the user's recent requests saved before compaction and restored after it
#   - a nudge to update the notes whenever Claude commits work
#   - a /checkpoint command to save notes on demand
#
# Usage:
#   bash install.sh             install or update (safe to re-run)
#   bash install.sh status      show what is installed
#   bash install.sh uninstall   remove it again
#
# Cloud sessions: paste this whole file into the environment's setup script.
#
# GENERATED by build.sh from install.template.sh; edit those, not install.sh.
set -euo pipefail

CLAUDE_HOME="$HOME/.claude"
GATEWAY="$CLAUDE_HOME/hooks/memory_gateway.py"
SKILL_DIR="$CLAUDE_HOME/skills/checkpoint"
SETTINGS="$CLAUDE_HOME/settings.json"
MARKER="installed by claude-memory-gateway"

# ---- EMBEDDED FILES ----

need_python() {
  if ! command -v python3 >/dev/null 2>&1; then
    echo "memory-gateway: python3 is required but was not found." >&2
    exit 1
  fi
}

# Add (mode=add) or remove (mode=remove) our hook entries, leaving any other
# hooks in settings.json untouched.
edit_settings() {
  python3 - "$SETTINGS" "$GATEWAY" "$1" <<'PY'
import json, os, sys
path, script, mode = sys.argv[1:]
try:
    with open(path) as fh:
        settings = json.load(fh)
except FileNotFoundError:
    settings = {}
hooks = settings.setdefault("hooks", {})
for event, arg in (("SessionStart", "restore"), ("PreCompact", "snapshot"), ("Stop", "stop")):
    groups = hooks.setdefault(event, [])
    for group in groups:
        group["hooks"] = [h for h in group.get("hooks", [])
                          if "memory_gateway.py" not in h.get("command", "")]
    groups[:] = [g for g in groups if g.get("hooks")]
    if mode == "add":
        groups.append({"matcher": "", "hooks": [
            {"type": "command", "command": f'python3 "{script}" {arg} --global'}]})
    if not groups:
        del hooks[event]
if not hooks:
    settings.pop("hooks")
os.makedirs(os.path.dirname(path), exist_ok=True)
with open(path, "w") as fh:
    json.dump(settings, fh, indent=2)
    fh.write("\n")
PY
}

skill_is_ours() {
  [ ! -e "$SKILL_DIR/SKILL.md" ] || grep -q "$MARKER" "$SKILL_DIR/SKILL.md"
}

do_install() {
  need_python
  mkdir -p "$CLAUDE_HOME/hooks"
  write_gateway "$GATEWAY"
  if skill_is_ours; then
    mkdir -p "$SKILL_DIR"
    write_skill "$SKILL_DIR/SKILL.md"
  else
    echo "memory-gateway: you already have your own /checkpoint skill; left it alone."
  fi
  edit_settings add
  echo "memory-gateway: installed. New Claude Code sessions will use it."
}

do_uninstall() {
  need_python
  [ -f "$SETTINGS" ] && edit_settings remove
  rm -f "$GATEWAY"
  if [ -e "$SKILL_DIR/SKILL.md" ] && skill_is_ours; then rm -rf "$SKILL_DIR"; fi
  echo "memory-gateway: removed. Saved snapshots stay in $CLAUDE_HOME/memory-gateway/ (delete it if you like)."
}

do_status() {
  local ok=1
  if [ -f "$GATEWAY" ]; then echo "hook script:     $GATEWAY"; else echo "hook script:     MISSING"; ok=0; fi
  if [ -f "$SKILL_DIR/SKILL.md" ] && grep -q "$MARKER" "$SKILL_DIR/SKILL.md"; then
    echo "/checkpoint:     $SKILL_DIR/SKILL.md"
  else
    echo "/checkpoint:     not installed by memory-gateway"
  fi
  local count=0
  [ -f "$SETTINGS" ] && count=$(grep -c "memory_gateway.py" "$SETTINGS" || true)
  echo "hooks in settings: $count of 3"
  [ "$count" = 3 ] || ok=0
  command -v python3 >/dev/null 2>&1 && echo "python3:         $(command -v python3)" || { echo "python3:         MISSING"; ok=0; }
  if [ "$ok" = 1 ]; then echo "status: installed"; else echo "status: not installed (run: bash install.sh)"; return 1; fi
}

case "${1:-install}" in
  install) do_install ;;
  uninstall) do_uninstall ;;
  status) do_status ;;
  *) echo "usage: bash install.sh [install|status|uninstall]" >&2; exit 2 ;;
esac
